Update workflows to get version from Cargo.toml (#59)
* update workflows for test_build

* update workflows for deploy

* build_nohealthcheck: false

* build_with_tmpfs: true

* add binary build workflow

* add sudo to apt- commands

* add deps

* multi-arch dependencies

* multi-arch build troubleshooting

* multi-arch build tshooting

* multi-arch troubleshooting

* tshoot

* troubleshoot cross-build

* add comment

* tshoot

* remove i386

* troubleshooting

* troubleshoot

* troubleshoot

* troubleshoot

* add build artifact upload

* change name

* use pre-built binary

* move uses to step

* troubleshooting

* troubleshoot

* add env

* test artifacts

* cache binaries

* utilise action cache

* disable ssh

* fix needs

* remove flake-8 linting

* fix build

* deal with multi-arch in a hacky way

* ensure binaries are executable & clean up

* exit 1 on fail

* test release deploy

* naming

* troubleshoot release

* troubleshoot release

* change order of jobs

* add tag

* add tag commit

* create tag

* add checkout

* troubleshoot release

* final clean up

* fix local builds

* fix typo

* add target back in

* consolidate binaries

* correct binary path

* fix binary filenames

* change name (pedantic)

diff --git a/rootfs/etc/services.d/acars_router/run b/rootfs/etc/services.d/acars_router/run
--- a/rootfs/etc/services.d/acars_router/run
+++ b/rootfs/etc/services.d/acars_router/run
@@ -1,4 +1,20 @@
 #!/usr/bin/with-contenv bash
 # shellcheck shell=bash
 
-/opt/acars_router
+if /opt/acars_router.amd64 --version > /dev/null 2>&1; then
+    /opt/acars_router.amd64
+
+elif /opt/acars_router.arm64 --version > /dev/null 2>&1; then
+    /opt/acars_router.arm64
+
+elif /opt/acars_router.armv7 --version > /dev/null 2>&1; then
+    /opt/acars_router.armv7
+
+elif /opt/acars_router --version > /dev/null 2>&1; then
+    /opt/acars_router
+
+else
+    >&2 echo "ERROR: Unsupported architecture"
+    sleep 60
+    exit 1
+fi
