troubleshoot release

diff --git a/.github/workflows/on_pr.yaml b/.github/workflows/on_pr.yaml
--- a/.github/workflows/on_pr.yaml
+++ b/.github/workflows/on_pr.yaml
@@ -216,8 +216,26 @@ jobs:
       #   with:
       #     limit-access-to-users: mikenye
 
-      # TEST RELEASES - WILL MOVE TO DEPLOY.YAML WHEN READY
+  release_binaries:
+    name: Release Binaries
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Cache cargo build output
+        id: get_cache
+        uses: actions/cache@v3
+        with:
+          path: target/
+          key: ${{ github.run_id }}
+
+      - name: Check cache
+        if: steps.get_cache.outputs.cache-hit != 'true'
+        run: |
+          echo "::error title=${{ github.job }}: Could not get binaries from action cache"
+          exit 1
+
       - name: Prepare binary release tarballs
+        if: steps.get_cache.outputs.cache-hit == 'true'
         run: |
           ORIGDIR=$(pwd)
           # Make release tarballs
@@ -233,6 +251,7 @@ jobs:
           popd
 
       - name: Get binary version from Cargo.toml
+        if: steps.get_cache.outputs.cache-hit == 'true'
         id: release_version
         run: |
           # Get version from Cargo.toml
@@ -240,15 +259,16 @@ jobs:
           echo "::set-output name=RELEASE_VERSION::$RELEASE_VERSION"
           
       - name: Create binary release
+        if: steps.get_cache.outputs.cache-hit == 'true'
         uses: ncipollo/release-action@v1
         with:
           artifacts: ./release/*.tar.xz
-          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
+          token: ${{ secrets.GITHUB_TOKEN }}
           name: ${{ steps.release_version.outputs.RELEASE_VERSION }}
 
   test_docker_image_build:
     name: Test Docker Image Build
-    needs: [hadolint, binary_build]
+    needs: [hadolint, binary_build, test_functionality]
     uses: sdr-enthusiasts/common-github-workflows/.github/workflows/build_and_push_image.yml@main
     with:
       get_version_method: cargo_toml_file_in_repo:file=/Cargo.toml
@@ -257,81 +277,3 @@ jobs:
       cache_enabled: true
       cache_path: target/
       cache_key: ${{ github.run_id }}
-
-    # strategy:
-    #   matrix:
-    #     docker-platform:
-    #       - linux/amd64
-    #       - linux/arm64
-    #       # - linux/arm/v6
-    #       - linux/arm/v7
-    #       - linux/i386
-    # steps:
-    #   # Check out our code
-    #   - name: Checkout
-    #     uses: actions/checkout@v3
-    #     with:
-    #       fetch-depth: 0
-
-    #   # List of files to check to trigger a rebuild on this job
-    #   - name: Get specific changed files
-    #     id: changed-files-specific
-    #     uses: tj-actions/changed-files@v23.2
-    #     with:
-    #       files: |
-    #         Dockerfile
-    #         acars_router
-    #         !*.md
-    #         !*.MD
-
-    #   # https://github.com/marketplace/actions/docker-on-tmpfs
-    #   # https://github.com/rust-lang/cargo/issues/8719
-    #   # https://github.com/rust-lang/cargo/issues/9545
-
-
-
-      # - name: Run Docker on tmpfs
-      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
-      #   uses: JonasAlfredsson/docker-on-tmpfs@v1
-      #   with:
-      #     tmpfs_size: 5
-      #     swap_size: 4
-      #     swap_location: "/mnt/swapfile"
-
-      # # Set up QEMU for multi-arch builds
-      # - name: Set up QEMU
-      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
-      #   uses: docker/setup-qemu-action@v2
-
-      # # Set up buildx for multi platform builds
-      # - name: Set up Docker Buildx
-      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
-      #   id: buildx
-      #   uses: docker/setup-buildx-action@v2
-
-      # # Build
-      # - name: Test Build
-      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
-      #   uses: docker/build-push-action@v3
-      #   with:
-      #     context: .
-      #     file: ./Dockerfile
-      #     no-cache: true
-      #     platforms: ${{ matrix.docker-platform }}
-      #     push: false
-
-      # # Patch dockerfile to remove healthcheck
-      # - name: Patch Dockerfile to remove healthcheck
-      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
-      #   run: sed '/^HEALTHCHECK /d' < Dockerfile > Dockerfile.nohealthcheck
-
-      # # Build nohealthcheck
-      # - name: Test Build nohealthcheck
-      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
-      #   uses: docker/build-push-action@v3
-      #   with:
-      #     context: .
-      #     file: ./Dockerfile.nohealthcheck
-      #     no-cache: true
-      #     platforms: ${{ matrix.docker-platform }}
-      #     push: false
